#!/usr/bin/env python3
import os
import sys


script_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, os.path.join(script_dir, "src", "python"))

from cli import main


if __name__ == "__main__":
    sys.exit(main())
